### ISSUE TITLE
Missing optional hub mission objectives

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#19]
- Attilan: Crystal asks the players to research where Medusa went. * .. Reported by: metal venger1
- Valhalla: Weasel asks the player to research a password. ...................... Reported by: Outsider, ak2yny

\* Medusa appears in phase 2 regardless, whether this mission was completed or not. Doesn't break the story though, because Medusa was corrupted and most likely not at the location anymore anyway.

**Comment by JordanLeich** [comment]
I did some looking into this and found exactly why both of these optional hub mission objectives are missing in game. The reason why is because there is no act3_valhalla.engb or act4_attilan.engb hub files found in data/missions. What's interesting however is that there are act1_stark.engb, act2_strange.engb, and an act5_doomstark.engb hub files containing hub related objectives. The only objective I found remotely similar to the "Valhalla: Weasel asks the player to research a password." optional objective is the optional objective called Nowhere to Hide: Determine the safest place for Weasel to hide from SHIELD agents. Luckily, this optional objective is found in act2_strange.engb since its a hub related objective. So going off of this and using somewhat of that existing code, here would be how the code would like if there was a act3_valhalla.engb file in data/missions:

"OBJECTIVE": {
            "descname": "Find the password",
            "description": "Find a password for Weasel.",
            "enabled": false,
            "major": false,
            "name": "valhalla_obj20",
            "optional": true,
            "parentname": "valhalla_obj0",
            "rep": 5,
            "type": "normal",
            "zone": "valhalla2"
        },

Here's how the code would look if there was a act4_attilan.engb file in data/missions:

"OBJECTIVE": {
            "descname": "Locating Medusa",
            "description": "Research where Medusa went.",
            "enabled": false,
            "major": false,
            "name": "attilan_obj20",
            "optional": true,
            "parentname": "attilan_obj0",
            "rep": 5,
            "type": "normal",
            "zone": "attilan2"
        },

**Comment by ak2yny** [comment]
Yes, that's how this works. One would also have to add the new hub mission files to missions.xmlb, and probably packages.
Do the existing hub missions have an icon? (One would have to add icons for the new ones, if yes.)

Are we ready to test the limits with them (although, the Outsider might already have found that limit).

**Comment by JordanLeich** [comment]
> Yes, that's how this works. One would also have to add the new hub mission files to missions.xmlb, and probably packages.
> 
> Do the existing hub missions have an icon? (One would have to add icons for the new ones, if yes.)
> 
> 
> 
> Are we ready to test the limits with them (although, the Outsider might already have found that limit).

I would assume they already have icons for those hub objectives but if not, we can add them. Maybe it's best we ask Outsider what the limits are regarding mission objectives first.

**Comment by JordanLeich** [comment]
@ak2yny Here's an example of one of the optional objectives in the act 2 strange hub, you'll notice it just uses the same icon as the critical objective. So if we add the act 3 and act 4 optional objectives then we can just use the same icon used for the hub critical objective.

![Game exe Screenshot 2022 10 29 - 00 02 06 32](https://user-images.githubusercontent.com/57107961/198813131-48ba8d7b-90dd-42a7-9b04-b30cdb43e2c1.png)

**Comment by JordanLeich** [comment]
I put together a sample act3_valhalla.engb and act4_attilan.engb hub files used in data/missions. I may try taking a look at what else needs to be added in terms of adding to missions.xmlb and probably packages.

[Data folder optional hub objectives.zip](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/9892980/Data.folder.optional.hub.objectives.zip)

**Comment by JordanLeich** [comment]
Ok I added a sample act3_valhalla.engb or act4_attilan.engb hub files found in data/missions folder. I also added act3_valhalla and act4_attilan to missions.xmlb. I'm not sure what to do with the map packages like if we want/need to add any custom scripts so I didn't touch anything packages wise except I noticed that attilan2.pkgb was already modified with ocp so I used that one instead of the vanilla file.

Here is everything I have worked on so far, please take a look when you get the chance. 

[Optional Objectives.zip](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/9893005/Optional.Objectives.zip)

**Comment by ak2yny** [comment]
Looking good so far. A few things to mention:
- act 3 and 4 hubs don't have any missions (critical or otherwise), and therefore no icons.
- I don't know what is required to make extra objectives turn up with new icons. We'll have to try.
- I checked, and missions don't seem to be in packages at all (you probably realized that since the packages you included are unmodified)
- The numbering of objectives starts with 10, and not 20. I don't know why they added a 0, but it makes more sense to start with 10.
- Opening, updating, and completing objectives is made with scripts. To make these work when extracting directly, we need to add them to loadpoint scripts.
- There is an quest with icon, which carries over multiple acts. What quest is that? Shall we make the BW quest like that as well?

**Comment by JordanLeich** [comment]
![image](https://user-images.githubusercontent.com/57107961/198840185-d0171f59-e53d-4274-a4a2-14b77a649453.jpeg)

This shows where the icons are stored at to be accessed for objectives.
I'm not sure what quest that is but yes we should make the BW quest similar to that since the BW quest involving Weasel starts at act1 and ends at act3.

**Comment by JordanLeich** [comment]
Here is what we have so far:

- [ ] Successfully added both of Act 1s Weasel objectives to be actually optional to show up and update in game and rewards the player with reputation points.
- [ ] Added a brand new optional objective for Act 3 Heimdall to bring his horn back to him.
- [ ] The finale of the Weasel questline involving Black Widow is now completable and an optional objective that rewards the player with reputation points.

Issues:

- [ ] Act 3 Niffleheim for whatever reason is not assigned a quest/objective icon.
- [ ] The new objective maps that were added are Act 3 Valhalla and Act 4 Attilan, both of these need quest/objective icons in the objective menu. We also need to figure out how to make them show up in the objectives menu along with Asgard Mission or Shiar Mission for example.
- [ ] Currently, the Act 4 Attilan optional objective is not completable due to improper coding in the attilan2.py file. The quest can be started successfully however when first talking to Crystal in Attilan but cannot be completed yet.

[Optional Objectives.zip](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/9955255/Optional.Objectives.zip)

**Comment by ak2yny** [comment]
The Outsider just informed me that he made everything work, while working on the EXG. Will share/upload the files as soon as it's available.

**Comment by JordanLeich** [comment]
> The Outsider just informed me that he made everything work, while working on the EXG. Will share/upload the files as soon as it's available.

That's great news, thanks.

**Comment by JordanLeich** [comment]
[BETA Optional Objectives.zip](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/10340635/BETA.Optional.Objectives.zip)

Medusa questline in act 4 Attilan is now completable, thanks to Outsider.

**Comment by JordanLeich** [comment]
completed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/8e37d194f2a8cccaac8e1035985b169431a28467
