### ISSUE TITLE
Loading Screen Bugs

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#27]
Reports by UltraMegaMagnus

- [ ] add [Hawkeye & Mephisto loadscreen fix](https://discord.com/channels/449510825385000960/929457958159548506/929607343564533810)
- [ ] Moon Knight loadscreen apparently not showing. Maybe we can test if it loads by finishing his simulator mission?

**Comment by JordanLeich** [comment]
I will work on fixing and testing this.

**Comment by JordanLeich** [comment]
So I did test playing the Moon Knight simulator mission and his loading screen worked at the end. The OCP is missing the 4101.igb file simply because the base vanilla game already includes it (no fix needed). Mephistos loading screens: 7901.igb is already included in the base game. The OCP boss_meph.igb is already included in the OCP so Mephistos should not need any fixing with his loading screens. Same thing applies for Hawkeyes loading screen, he does not need a fix either.
