### ISSUE TITLE
Thor bug

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#44]
Report by Cyborg Sun

Thor has an extra point on "Hammer Toss" that shouldn't be there in Easy-Normal difficulties (I checked all the other base 36 characters and most of the XML ones, I think this is the sole move that's like this, you can double-check everyone if you wish however).

![93D9BCBA-9BB8-4610-83E5-EEFAD5F189F4](https://user-images.githubusercontent.com/57107961/216676860-e249cff2-f1b6-4411-80aa-8d839a00e972.png)

**Comment by ak2yny** [comment]
Thor, Mr. Fantastic, and Magma.
The last three levels (cost) should always be 1-4-1 (cost 3 and 4). The last one is cost 4, and the other five are cost 3 - 1 for normal difficulty, and 4 for hard difficulty. The powers with the issue are all 4-1-1, so this must be some sort of typo.
I didn't make a change here, because I'm still unsure about the latest change in talents with the value descriptions.

**Comment by JordanLeich** [comment]
Fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/27da5cd4fb5bcbbdb2573e65e3143341b2aaee42
