### ISSUE TITLE
Hawkeye's P1 Multishot sound issue

### ISSUE THREAD

**Issue by UltraMegaMagnus** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#51]
When holding Multishot power, sound is looping and is noisy, unlike the Remastered version that seems to play only once when fully charged, then quiet when holding the power.
https://www.youtube.com/watch?v=z-6aBJ6u2A4&feature=youtu.be

**Comment by ak2yny** [comment]
Can someone provide audio or video of how it's supposed to sound?
Maybe how it is in the OCP as well.

**Comment by ak2yny** [comment]
UltraMegaMagnus made a video for me, thanks.

This sound is something that [I added](https://marvelmods.com/forum/index.php/topic,10936.msg199765.html#msg199765). (links to modders corner, must have access to see)
I re-visited the code and saw that the original powerstyle had that loop sound, but only the stop triggers. It seems like a perfect loop sound code, but the start trigger is missing. I am 100% sure that the GE devs took that loop sound out for some reason. I know that the Xbox 360 loop sounds work differently (probably the loop flag doesn't work at all). So the devs likely took that out because they didn't have the time to fix that for the 360. Hawkeye is originally a PSP character, and that loop sound code might be coming from there.

**Comment by ak2yny** [comment]
Not all charge powers have a looping sound, and this particular sound may be a little too noisy.
It's a fix in the code though, and since players release the button when charged, this makes minimal difference. I suggest we leave it in.
