### ISSUE TITLE
New Daredevil Issues

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#58]
~~Collecting all character bugs that we find. I thought that there was an open issue like that already, but I couldn't find it. Let's merge this one in case it exists.~~
Edit: Found #23 . Merged.

- [x] Daredevil: If he dies while restraining a victim with his billy club whip / wire, then the victim is not released and is stuck until someone kills them. (@techurious ) -- [possible solution](https://discord.com/channels/@me/797771078033211392/1183905855788298260) (link works only for ak2yny)

**Comment by ak2yny** [comment]
> If it's not clear from the description, I'm going to commit the fix myself.

I'd appreciate that.

**Comment by techurious** [comment]
I also noticed another bug in Power 3 (that I created back in the day when attempting to re-bolt the cable effect from Bip01 R Hand to fx02). For some reason if you try to use this power immediately after spawning, the effect will appear incorrectly. But if you use Power 2 before that, then subsequent uses of Power 3 will display normally, with the cable bolted to fx02 as it should. I'm guessing that's why in the vanilla game the effect was bolted to Bip01 R Hand for Power 3 to avoid this issue. 

I don't know what's causing this bug and why in the case of Power 2 "bolt = fx02" works from the start but for Power 3 it appears weird first. My only theory is that it has to do with the timing of the animation.
