### ISSUE TITLE
NPCstat improvements (less NPCs allow more herostat entries)

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#8]
Author: UMM, ak2yny

_UMN note, current OCP with 270 entries is good enough._

---------------------------------------------

remove more NPCs that are unused or unnecessary: 

- [x] `Deathbird_npc`
- [x] `vv_ironmandroid_b` + `c`
- [x] `JeanSimple` (only used in the NPC name change, `JeanGrey` is the main name used in the game).
Check the [Phoenix NPC name change](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/10367180/Phoenix.NPC.name.change.zip) for any entries of `JeanSimple`, and change them to `JeanGrey`, if necessary.

(Outsider was working on a version as well)

**Comment by ak2yny** [comment]
[Report](https://discord.com/channels/449510825385000960/449511007811796993/1038005517785763850) of NPCs that can be in T-Pose because of wrong animation file references in NPCstat. By metal venger1

Problematic NPCs:
- [ ] Everyone using `00_testguy`, incl. Corsair and Dum Dum Dugan : the animation file is missing
- [ ] Arcade : `102_arcade` is missing but the NPC never needs animations (HUD and name only)
- [ ] Attilan Civilians : `31_atlantean` is missing - HUB NPCs should not need animation files
- [ ] Clea : `151_clea` is missing - HUB NPCs should not need animation files
- [ ] Crystal : `64_crystal` is missing - HUB NPCs should not need animation files
- [ ] Karnak : `73_karnac` is missing - HUB NPCs should not need animation files
- [ ] Triton : `58_triton` is missing - HUB NPCs should not need animation files
- [ ] Volla : `145_volla` is missing, issues confirmed by metal venger1
- [ ] Watcher : `109_uata_the_watcher` is missing but he's assigned all animations through scripts
- [ ] Senator Kelly : `76_senator_Kelly` is missing, issues confirmed by metal venger1
- [ ] Stark Tower Office Workers : `158_OfficeWorkerMale` is missing - HUB NPCs should not need animation files
- [ ] Stark Tower Office Workers : `159_OfficeWorkerFemale` is missing - HUB NPCs should not need animation files
- [ ] Stark Tower Lab Technicians : `75_lab_technician_male` should be `74_lab_technician_male` - HUB NPCs should not need animation files
- [ ] Stark Tower Lab Technicians : `74_lab_technician_female` should be `75_lab_technician_female` - HUB NPCs should not need animation files
- [ ] Luke Cage : `15701_luke_cage` should be `157_luke_cage` - NPC never needs animations (HUD and name only in SIM)
- [ ] Spider-Woman : `38_spiderwoman` should be `38_spider_woman` - HUB NPCs should not need animation files

**Comment by ak2yny** [comment]
Reports by UltraMegaMagnus:

- [ ] `NickFuryCombatNPC` lists `fightstyle_hero` talent, this only exist in XML, safe to delete, but not sure if a proper fightstyle should be added instead (probably `fightstyle_default`).
Upon further inspection this `NickFuryCombatNPC` should be the one from Doomstark survival part, this NPC only follows us during the fight and nothing else.
Since this NPC has no combat capabilities, `monst_dmg_XXX` might be removable.
- [ ] Dark Thor uses `fightstyle_default` & `fightstyle_villain` talent, he should be only using `fightstyle_villain` I think. Vanilla issue.
Remove the menuonly segment:
```
      Multipart {
      health = 0 ;
      hideskin = hammer_back_segment ;
      menuonly = true ;
      showskin = hammer_segment ;
      }
```
- [ ] Dark Spider-Man uses `fightstyle_villain_Fast` & `fightstyle_villain` talent, he should be only using `fightstyle_villain_Fast` I think. Vanilla issue.
- [ ] `FenrisWolf_b` using `9803.igb` skin is possibly unused and could be removed from maps files, etc. The 9803 skin crashes the game?

**Comment by ak2yny** [comment]
`FenrisWolf_b` is used and working. `9805.igb` seems to be a leftover skin, which is not in NPCstat or packages.

**Comment by ak2yny** [comment]
Done 1e4e85e4013c1cf5e279add6b090c379fe155b50

**Comment by ak2yny** [comment]
There's at least one NPC that we still should eliminate, which is the duplicate NPC Ghost Rider (Simple and NPC). I don't know what each role is, like why there are two, but I'm 99% that this is one NPC that should be removed. I might re-open the issue sometime.

We also should check again for other NPCs to remove. The EXG NPCstat might help (but we shouldn't remove as many, since the EXG removed some variety and that mod or NPCstat can always be used separately as well).
